### ISSUE TITLE
X5 레지스터에 로드된 값은 ?

### ISSUE THREAD

**Issue by aireat** [iamroot16a/study#2]
```  
adrp	x5, __idmap_text_end 
```
위의 명령어 실행 후 X5 레지스터에 로드된 값은 무엇일까요 ?

**Comment by leeseungcheol** [comment]
https://github.com/torvalds/linux/commit/5dfe9d7d23c26d029415379630523f141a748c5b
위 커밋이 힌트가 될 수있을것 같은데 몇번 읽어봐도 잘모르겠네요.
기존에 전체 커널이미지에 대한 확장된 idmap을 쓰다가 뭔가 부작용때문에 idmap.text 섹션을 추가하고
KERNEL_START, KERNEL_END를 idmap_start, idmap_end로 바꾼것같습니다.

혹시 이해되시는분 코멘트좀...

**Comment by aireat** [comment]
X5 = 현재 PC 값 (상위 31 bits) + (__idmap_text_end 이 위치한 4KB 블록의 시작주소)

자세한 내용은 [ARD ARDP ADRL](https://github.com/iamroot16a/study/wiki/ARD_ADRP_ADRL) 참조 하십시오.  

이 이슈도 Close 하겠습니다.
