### ISSUE TITLE
ARMv8 아키텍쳐에서 instruction들은 왜 전부 32bit인가?

### ISSUE THREAD

**Issue by leeseungcheol** [iamroot16a/study#3]

**Comment by leeseungcheol** [comment]
전부 32bit는 아니네요...

**Comment by aireat** [comment]
추가 논의를 위해 이슈를 다시 open 합니다.

**Comment by aireat** [comment]
ARMv8-A Architecture Reference Manual (C1.1 Introduction, page 112)  
여기에 보면 AArch64 명령어는 32bit의 길이를 갖는다. 라고 나와 있습니다.

A64 명령어는 32bit 길이를 갖는 것으로 이 이슈는 close 하겠습니다.
